[build]
   functions = "functions"

[functions]
  external_node_modules = ["express", "mongodb"]
  node_bundler = "esbuild"
 

[[redirects]]
  force = true
  from = "/server/*"
  status = 200
  to = "/.netlify/functions/server/:splat"