[build]
   functions = "functions"

[functions]
  external_node_modules = ["express", "mongodb"]
  node_bundler = "esbuild"
 

[[redirects]]
  force = true
  status = 200
  from = "/home/*"
  to = "/.netlify/functions/server/:splat"

[[redirects]]
  force = true
  status = 200
  from = "/user/*"
  to = "/.netlify/functions/routes/users/:splat"